Ignore test.
java.lang.Exception: Unexpected exception, expected<ch.cyberduck.core.exception.ConflictException> but was<ch.cyberduck.core.exception.ConnectionRefusedException>
	at ch.cyberduck.core.worker.SingleTransferWorkerTest.testTransferredSizeRepeat(SingleTransferWorkerTest.java:161)
Caused by: java.net.SocketException: Connection timed out (Write failed)
	at ch.cyberduck.core.worker.SingleTransferWorkerTest.testTransferredSizeRepeat(SingleTransferWorkerTest.java:161)