Ignore test failure with fail on Windows CI.
ch.cyberduck.core.exception.ConnectionTimeoutException: Connection timed out
	at ch.cyberduck.core.worker.ConcurrentTransferWorkerTest.testConcurrentSessions(ConcurrentTransferWorkerTest.java:99)
Caused by: java.net.SocketTimeoutException: Read timed out
	at ch.cyberduck.core.worker.ConcurrentTransferWorkerTest.testConcurrentSessions(ConcurrentTransferWorkerTest.java:99)