Revert.
I’m trying to retrieve a private key from my KeychainStore on OSX:

...
store = KeyStore.getInstance("KeychainStore“, "Apple“);
store.load(null, null)
store.getKey("clientAlias", "null".toCharArray()) // password is not relevant to access Keychain
…

As of version 1.53 (1.52 works fine) I get the following exception:

org.bouncycastle.crypto.InvalidCipherTextException: pad block corrupted

It happens in BaseBlockCipher$BufferedGenericBlockCipher in the doFinal method. According to the debugger the cipher is PaddedBufferedBlockCipher.

The self-signed client certificate I’m testing with is attached (password test).

Without registering the BC provider things work fine too. Could not find any related entries in the release notes.